// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWV-0nFVZR3J3zMxwBnzVab3WWB-FLZU',
    appId: '1:25867044109:web:ac4f52a0a6f1587fd89c44',
    messagingSenderId: '25867044109',
    projectId: 'notif-72c72',
    authDomain: 'notif-72c72.firebaseapp.com',
    storageBucket: 'notif-72c72.firebasestorage.app',
    measurementId: 'G-ZMHQJ91ENM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYZpiPXam7Zxx1NqockQiCkc9jPMMbAY',
    appId: '1:25867044109:android:a76a93a46fa5a6e5d89c44',
    messagingSenderId: '25867044109',
    projectId: 'notif-72c72',
    storageBucket: 'notif-72c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHhU5XN9aHPfSP-YheBgKPXsDIHua8-bQ',
    appId: '1:25867044109:ios:968ad17cf174c3c6d89c44',
    messagingSenderId: '25867044109',
    projectId: 'notif-72c72',
    storageBucket: 'notif-72c72.firebasestorage.app',
    iosClientId: '25867044109-9mf69qo5brelf4rjthfdjsreeg56769h.apps.googleusercontent.com',
    iosBundleId: 'com.notif.notifios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHhU5XN9aHPfSP-YheBgKPXsDIHua8-bQ',
    appId: '1:25867044109:ios:c738977fff0b9cf0d89c44',
    messagingSenderId: '25867044109',
    projectId: 'notif-72c72',
    storageBucket: 'notif-72c72.firebasestorage.app',
    iosClientId: '25867044109-jut2sbsq5c54nte9vi0ffirokgod9mso.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkWV-0nFVZR3J3zMxwBnzVab3WWB-FLZU',
    appId: '1:25867044109:web:4896e9229532c57dd89c44',
    messagingSenderId: '25867044109',
    projectId: 'notif-72c72',
    authDomain: 'notif-72c72.firebaseapp.com',
    storageBucket: 'notif-72c72.firebasestorage.app',
    measurementId: 'G-M5KZB6485G',
  );
}
